### ISSUE TITLE
Initial camera transform values 

### ISSUE THREAD

**Issue by piedoom** [mcpar-land/bevy_fly_camera#18]
I am trying to create a camera with a default position, for ease of use. I noticed that as soon as the camera is enabled, the initial set rotation is discarded. I suspect this has to do with something like `pitch` and `yaw` defaulting to 0 and resetting any rotations.

For reproducing, try the following:

```
// ... create the camera
camera.transform = Transform::from_xyz(10f32, 10f32, 10f32).looking_at(Vec3::ZERO, Vec3::Y);
```

**Comment by Gnurfos** [comment]
Pull request #15 fixes this
