### ISSUE TITLE
Friction not applied

### ISSUE THREAD

**Issue by tjatkowski** [mcpar-land/bevy_fly_camera#4]
When you move in some direction, then suddenly decide to move the opposite direction, (for example: holding D, then suddenly changing it to holding A), friction is not applied during slowing down, so it takes long time. (It's faster to change direction by completely releasing every button, and then going opposite direction when you're fully stopped).

**Comment by mcpar-land** [comment]
Fixed this with https://github.com/mcpar-land/bevy_fly_camera/commit/73429cbebad3adefe320fdd3d8324e36d515b296, thank you for your report!
