### ISSUE TITLE
Explain speed and max_speed

### ISSUE THREAD

**Issue by etam** [mcpar-land/bevy_fly_camera#8]
`max_speed` is quite self-explanatory, but having played with it's value I see no effect.

`speed` would mean for me the actual temporary speed, but by default the camera is not moving. It's only moving, when a key is pressed. Isn't it more about acceleration, than speed?

Also the default value mentioned in comments doesn't match the actual default value.

**Comment by mcpar-land** [comment]
Yeah, `speed` is definitely a misnomer. It should be more like "acceleration."

**Comment by mcpar-land** [comment]
I've changed this variable to `accel` in [this commit](https://github.com/mcpar-land/bevy_fly_camera/commit/f18834eaa2c68022fa384ba934d10cb47921b630#diff-b1a35a68f14e696205874893c07fd24fdb88882b47c23cc0e0c80a30c7d53759R74). Thanks for the heads up about it!
